/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.jetsetmagazine.gui;

/**
 *
 * @author Talel
 */
public class interfaceclient extends javax.swing.JFrame {

    /**
     * Creates new form interfaceclient
     */
    public interfaceclient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMnews = new javax.swing.JMenuItem();
        jMactualite = new javax.swing.JMenuItem();
        jMintervie = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMsoirée = new javax.swing.JMenuItem();
        jMtheatre = new javax.swing.JMenuItem();
        jMcinema = new javax.swing.JMenuItem();
        jMconcert = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/jetsetmagazine/gui/jetsetmag.jpg"))); // NOI18N

        jMenu2.setText("Consultation rubriques");

        jMnews.setText("Consultation News");
        jMnews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnewsActionPerformed(evt);
            }
        });
        jMenu2.add(jMnews);

        jMactualite.setText("Consultation des Actualités");
        jMenu2.add(jMactualite);

        jMintervie.setText("Consultation des Interviews");
        jMintervie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMintervieActionPerformed(evt);
            }
        });
        jMenu2.add(jMintervie);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultation des Soirées");

        jMsoirée.setText("Consultation des soirées");
        jMsoirée.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsoiréeActionPerformed(evt);
            }
        });
        jMenu3.add(jMsoirée);

        jMtheatre.setText("Consultation des théatres");
        jMenu3.add(jMtheatre);

        jMcinema.setText("Consultation des cinéma");
        jMenu3.add(jMcinema);

        jMconcert.setText("Consultation des concerts");
        jMenu3.add(jMconcert);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnewsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnewsActionPerformed

    private void jMintervieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMintervieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMintervieActionPerformed

    private void jMsoiréeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsoiréeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMsoiréeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceclient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMactualite;
    private javax.swing.JMenuItem jMcinema;
    private javax.swing.JMenuItem jMconcert;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMintervie;
    private javax.swing.JMenuItem jMnews;
    private javax.swing.JMenuItem jMsoirée;
    private javax.swing.JMenuItem jMtheatre;
    // End of variables declaration//GEN-END:variables
}
